package com.fridgetoplate.interfaces;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fridgetoplate.model.Ingredient;
import com.fridgetoplate.model.Preference;
import com.fridgetoplate.utils.IngredientArrayConverter;

import lombok.Data;

@Data
public class Profile {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String profileId;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String displayName;

    @DynamoDBAttribute
    private String profilePicture;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = IngredientArrayConverter.class)
    private Ingredient[] ingredients;

    @DynamoDBAttribute
    private Preference preferences;
    
}