package com.fridgetoplate.interfaces;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fridgetoplate.utils.StringArrayConverter;

import lombok.Data;

@Data
public class RecipeDesc {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    protected String recipeId;

    @DynamoDBAttribute
    protected String name;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = StringArrayConverter.class)
    protected String[] tags;

    @DynamoDBAttribute
    protected String difficulty;
}
