package com.fridgetoplate.frontendmodels;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.fridgetoplate.interfaces.Ingredient;
import com.fridgetoplate.interfaces.Recipe;
import com.fridgetoplate.model.Review;

@DynamoDBTable(tableName = "recipes")
public class RecipeFrontendModel extends Recipe {

    private List<Review> reviews;

    // The getters
    @DynamoDBHashKey(attributeName = "recipeId")
    @DynamoDBAutoGeneratedKey
    public String getRecipeId() {
        return recipeId;
    }

    @DynamoDBAttribute(attributeName = "recipeImage")
    public String getRecipeImage() {
        return recipeImage;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "tags")
    public List<String> getTags() {
        return tags;
    }

    @DynamoDBAttribute(attributeName = "meal")
    public String getMeal() {
        return meal;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute(attributeName = "ingredients")
    public List<Ingredient> getIngredients() {
        return ingredients;
    }

    @DynamoDBAttribute(attributeName = "steps")
    public List<String> getSteps() {
        return steps;
    }

    @DynamoDBAttribute(attributeName = "prepTime")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    public Integer getPrepTime() {
        return prepTime;
    }

    @DynamoDBAttribute(attributeName = "servings")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    public Integer getServings() {
        return servings;
    }

    @DynamoDBAttribute(attributeName = "difficulty")
    public String getDifficulty() {
        return difficulty;
    }

    @DynamoDBAttribute(attributeName = "creator")
    public String getCreator() {
        return creator;
    }

    @DynamoDBAttribute(attributeName = "reviews")
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public List<Review> getReviews(){
        return this.reviews;
    }

    public void setReviews(List<Review> reviews) {
        this.reviews = reviews;
    }
}
