package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.Ingredient;

@DynamoDBTable(tableName = "ingredients")
public class IngredientModel extends Ingredient {
    
    private String recipeId;

    private String ingredientId;

    @DynamoDBHashKey(attributeName = "recipeId")
    public String getRecipeId() {
        return recipeId;
    }

    @DynamoDBRangeKey(attributeName = "ingredientId")
    @DynamoDBAutoGeneratedKey
    public String getIngredientId() {
        return ingredientId;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "amount")
    public Double getAmount() {
        return amount;
    }

    @DynamoDBAttribute(attributeName = "unit")
    public String getUnit() {
        return unit;
    }

    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId;
    }

    public void setIngredientId(String ingredientId) {
        this.ingredientId = ingredientId;
    }
}
