package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "ingredients")
public class Ingredient {
    
    @DynamoDBHashKey(attributeName = "ingredientId")
    @DynamoDBAutoGeneratedKey
    private String ingredientId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "amount")
    private Integer amount;

    @DynamoDBAttribute(attributeName = "unit")
    private String unit;

}
