package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.Ingredient;

@DynamoDBTable(tableName = "ingredients")
public class IngredientModel extends Ingredient {
    
    @DynamoDBHashKey(attributeName = "recipeId")
    private String recipeId;

    @DynamoDBRangeKey(attributeName = "ingredientId")
    @DynamoDBAutoGeneratedKey
    private String ingredientId;

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "amount")
    public Double getAmount() {
        return amount;
    }

    @DynamoDBAttribute(attributeName = "unit")
    public String getUnit() {
        return unit;
    }
}
