package com.fridgetoplate.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.RecipeDesc;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "meal_plans")
public class MealPlan {

    @DynamoDBHashKey(attributeName = "planId")
    @DynamoDBAutoGeneratedKey
    private String planId;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "dateTime")
    private String dateTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));

    @DynamoDBAttribute(attributeName = "breakfast")
    private RecipeDesc breakfast;

    @DynamoDBAttribute(attributeName = "lunch")
    private RecipeDesc lunch;

    @DynamoDBAttribute(attributeName = "dinner")
    private RecipeDesc dinner;

    @DynamoDBAttribute(attributeName = "snack")
    private RecipeDesc snack;
}
