package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.fridgetoplate.interfaces.MealPlan;

@DynamoDBTable(tableName = "meal_plans")
public class MealPlanModel extends MealPlan {

    @DynamoDBAttribute(attributeName = "breakfast")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private String breakfast;

    @DynamoDBAttribute(attributeName = "lunch")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private String lunch;

    @DynamoDBAttribute(attributeName = "dinner")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private String dinner;

    @DynamoDBAttribute(attributeName = "snack")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private String snack;
    

    // Getters
    @DynamoDBHashKey(attributeName = "planId")
    @DynamoDBAutoGeneratedKey
    public String getPlanId() {
        return planId;
    }

    @DynamoDBHashKey(attributeName = "username")
    public String getUsername() {
        return username;
    }

    @DynamoDBAttribute(attributeName = "date_Time")
    public String getDateTime() {
        return dateTime;
    }

    @DynamoDBAttribute(attributeName = "breakfast")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public String getBreakfast() {
        return breakfast;
    }

    @DynamoDBAttribute(attributeName = "lunch")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public String getLunch() {
        return lunch;
    }

    @DynamoDBAttribute(attributeName = "dinner")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public String getDinner() {
        return dinner;
    }

    @DynamoDBAttribute(attributeName = "snack")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public String getSnack() {
        return snack;
    }

    // setters
    @DynamoDBAttribute(attributeName = "breakfast")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public void setBreakfast(String breakfast) {
        this.breakfast = breakfast;
    }

    @DynamoDBAttribute(attributeName = "lunch")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public void setLunch(String lunch) {
        this.lunch = lunch;
    }

    @DynamoDBAttribute(attributeName = "dinner")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public void setDinner(String dinner) {
        this.dinner = dinner;
    }

    @DynamoDBAttribute(attributeName = "snack")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public void setSnack(String snack) {
        this.snack = snack;
    }

}
