package com.fridgetoplate.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.RecipeDesc;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "meal_plans")
public class MealPlan {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String planId;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String dateTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));

    @DynamoDBAttribute
    private RecipeDesc breakfast;

    @DynamoDBAttribute
    private RecipeDesc lunch;

    @DynamoDBAttribute
    private RecipeDesc dinner;

    @DynamoDBAttribute
    private RecipeDesc snack;

}
