package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.Notification;

@DynamoDBTable(tableName = "notifications")
public class NotificationModel extends Notification{
    
    private String userId;

    @DynamoDBHashKey(attributeName = "notificationId")
    @DynamoDBAutoGeneratedKey
    public String getNotificationId() {
        return notificationId;
    }    

    @DynamoDBAttribute(attributeName = "recipeId")
    public String getRecipeId(){
        return recipeId;
    }

    @DynamoDBAttribute(attributeName = "userName")
    public String getUserName(){
        return userName;
    }

    @DynamoDBAttribute(attributeName = "profilePictureUrl")
    public String getProfilePictureUrl(){
        return profilePictureUrl;
    }

    @DynamoDBAttribute(attributeName = "comment")
    public String getComment(){
        return comment;
    }

    @DynamoDBAttribute(attributeName = "notificationType")
    public String getNotificationType(){
        return notificationType;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public String getUserId(){
        return userId;
    }

    //Setters
    public void setUserId(String userId){
        this.userId = userId;
    }
}
