package com.fridgetoplate.model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "profiles")
public class Profile {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String profileId;
    
    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String profilePicture;

    @DynamoDBAttribute
    private Ingredient[] ingredients;

    @DynamoDBAttribute
<<<<<<< HEAD
    private Recipe[] preferences;

    @DynamoDBAttribute
    private Recipe[] create_recipes;
=======
    private Preference[] preferences;

    @DynamoDBAttribute
    private Recipe[] created_recipes;
>>>>>>> 29d0b008fbd90782385869c2ae572fad6fa884ed
}
