package com.fridgetoplate.model;

import java.util.List;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fridgetoplate.interfaces.Recipe;

@DynamoDBTable(tableName = "recipes")
public class RecipeModel extends Recipe {

    @DynamoDBAttribute(attributeName = "recipeId")
    @DynamoDBAutoGeneratedKey
    public String getRecipeId() {
        return recipeId;
    }

       @DynamoDBAttribute(attributeName = "recipe_image")
    public String getRecipeImage() {
        return recipeImage;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute(attributeName = "tags")
    public List<String> getTags() {
        return tags;
    }

    @DynamoDBAttribute(attributeName = "meal")
    public String getMeal() {
        return meal;
    }
    
    @DynamoDBAttribute(attributeName = "ingredients")
    public List<Ingredient> getIngredients() {
        return ingredients;
    }

    @DynamoDBAttribute(attributeName = "instructions")
    public List<String> getInstructions() {
        return instructions;
    }

    @DynamoDBAttribute(attributeName = "prep_time")
    public Integer getPrepTime() {
        return prepTime;
    }

    @DynamoDBAttribute(attributeName = "number_of_servings")
    public Integer getNumberOfServings() {
        return numberOfServings;
    }

    @DynamoDBAttribute(attributeName = "difficulty")
    public String getDifficulty() {
        return difficulty;
    }

    @DynamoDBAttribute(attributeName = "creator")
    public String getCreator() {
        return creator;
    }

    private Integer views = 0;
    @DynamoDBAttribute(attributeName = "views")
    public Integer getViews() {
        return views;
    }
}
