package com.fridgetoplate.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "recipes")
public class Recipe {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String recipeId;
    
    
    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String ingredients;

    @DynamoDBAttribute
    private String instructions;

}
