name: Development CI/CD

on:
  push:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  ci-workflow:
    uses: ./.github/workflows/ci-dev.yml
    secrets: inherit

  deploy-app:

    name: App Deployment
    needs: ci-workflow
    runs-on: ubuntu-latest
    environment: Development  
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Setup Enviroment File
      run: |
        printf "${{ secrets.ENV_FILE }}" > .env
      shell: bash

    - name: Install Dependencies
      run: npm install
      
    - name: Build App
      run: npm run build:app:dev

    - name: Deploy App
      run: aws s3 sync ./dist/apps/app s3://dev-fridgetoplate

  deploy_api:

    name: API Deployment
    needs: ci-workflow
    runs-on: windows-latest
    environment: Development

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1
    
      - name: Setup NodeJS and Cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Setup JDK 17 and Cache
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'      
    
      - name: Setup Enviroment File
        run: |
          printf "${{ secrets.ENV_FILE }}" > .env
        shell: bash
          
      - name: Setup NX
        run: npm install nx@latest

      - name: Setup Enviroment Files
        run: |
          printf "${{ secrets.API_APPLICATION_PROPERTIES }}" > apps/api/src/main/resources/application.properties
          cat apps/api/src/main/resources/application.properties
        shell: bash

      - name: Build API
        run: npm run build:api

      - name: Create ZIP Package
        run: Compress-Archive -Path ./apps/api/build/libs/* -DestinationPath ./deploy_package.zip

      - name: Upload API Package
        run: aws s3 cp deploy_package.zip s3://fridgetoplate-api-deploy-bucket

      - name: Create New API Version
        run: aws elasticbeanstalk create-application-version --application-name fridgetoplate --source-bundle S3Bucket="fridgetoplate-api-deploy-bucket",S3Key="deploy_package.zip" --version-label "dev-${{ github.sha }}" --description "commit-sha-${{ github.sha }}"

      - name: Deploy API
        run: aws elasticbeanstalk update-environment --environment-name dev-fridgetoplate-env --version-label "dev-${{ github.sha }}"