name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci-workflow:
    uses: ./.github/workflows/ci-prod.yml

  deploy-app:

    name: App Deployment
    needs: ci-workflow
    runs-on: ubuntu-latest
    environment: Production 
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: npm install
      
    - name: Build App
      run: npm run build:app:dev

    - name: Deploy App
      if: success()
      run: aws s3 sync ./dist/apps/app s3://fridgetoplate
