name: Development CI

on:
  push:
    branches: [ feat/* ]
  pull_request:
    branches: [ dev, feat/* ]
  workflow_call:

permissions:
  contents: read

jobs:
  test_build_api:

    name: Lint, Test & Build API
    runs-on: windows-latest
    environment: Development 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Setup JDK 17 and Cache
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup NX
      run: npm install nx@latest

    - name: Test API
      run: npm run test:api
      
    - name: Build API
      run: npm run build:api

    - name: SonarCloud Build and Analyze
      working-directory: apps/api/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
      run: ./gradlew build sonarqube --info

  test_build_app:

    name: Lint, Test & Build App
    runs-on: ubuntu-latest
    environment: Development 
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Lint App
      run: npx nx run app:lint

    - name: Test App
      run: npm run test:app
      
    - name: Build App
      run: npm run build:app:dev

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_APP }}
      with:
        projectBaseDir: apps/app/