name: Development CI

on:
  push:
    branches: [ feat/* ]
  pull_request:
    branches: [ dev, feat/* ]
  workflow_call:
    secrets:
      SONAR_TOKEN_API:
        required: true

permissions:
  contents: read

jobs:
  test_build_workspace:

    name: Lint, Test & Build Wokspace
    runs-on: ubuntu-latest
    environment: Development 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Setup JDK 17 and Cache
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Dependencies
      run: npm install

    - name: Lint App
      run: npx nx run app:lint

    - name: Test Workspace
      run: npm run test:app:ci

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage/lcov.info  
      
    - name: Build App
      run: npm run build:app:dev
      
    - name: Build API
      run: npm run build:api
