name: Production CI on PR

on:
    pull_request:
        branches: [ main ]

permissions:
  contents: read

jobs:
  test_build_api:

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup NX
      uses: nrwl/nx-set-shas@v3

    - name: Test API
      run: npm run test:api
      
    - name: Build API
      run: npm run build:api 

  test_build_app:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v23
      with:
        node-version: '16.x'

    - name: Setup NX
      uses: nrwl/nx-set-shas@v3

    - name: Install Dependencies
      run: npm install

    - name: Test App
      run: npm run test:app
      
    - name: Build App
      run: npm run build:app