name: Production CI

on:
  push:
    branches: [ dev, feat/* ]
  pull_request:
    branches: [ dev, feat/* ]

permissions:
  contents: read

jobs:
  test_build_api:

    runs-on: windows-latest
    environment: Production 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup NX
      uses: nrwl/nx-set-shas@v3

    - name: Test API
      run: npm run test:api
      
    - name: Build API
      run: npm run build:api

  test_build_app:

    runs-on: ubuntu-latest
    environment: Production 
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Setup NX
      uses: nrwl/nx-set-shas@v3

    - name: Install Dependencies
      run: npm ci

    - name: Test App
      run: npm run test:app:prod
      
    - name: Build App
      run: npm run build:app:prod