name: Production CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_build_api:

    runs-on: windows-latest
    environment: Production 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup NX
      run: npm install nx@latest

    - name: Test API
      run: npm run test:api
      
    - name: Build API
      run: npm run build:api

  test_build_app:

    runs-on: ubuntu-latest
    environment: Production 
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Test App
      run: npm run test:app
      
    - name: Build App
      run: npm run build:app:prod