name: Production CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_build_api:

    runs-on: windows-latest
    environment: Production 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - name: Setup JDK 17 and Cache
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup NX
      run: npm install nx@latest

    - name: Test API
      run: npm run test:api
      
    - name: Build API
      run: npm run build:api

  test_build_app:

    runs-on: ubuntu-latest
    environment: Production 
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Test App
      run: npm run test:app
      
    - name: Build App
      run: npm run build:app:prod